#pragma once
#include "imgui.h"
#include <string>

struct EditorTheme
{
	std::string EDITOR_FONT;
	std::string ICON_FONT;

	ImVec4 TEXT;
	ImVec4 TEXT_DISABLED;

	ImVec4 WINDOW_BG;
	ImVec4 CHILD_BG;
	ImVec4 POPUP_BG;

	ImVec4 BORDER;
	ImVec4 BORDER_SHADOW;

	ImVec4 FRAME_BG;
	ImVec4 FRAME_BG_HOVERED;
	ImVec4 FRAME_BG_ACTIVE;

	ImVec4 TITLE_BG;
	ImVec4 TITLE_BG_ACTIVE;
	ImVec4 TITLE_BG_COLLAPSED;

	ImVec4 MENU_BAR_BG;

	ImVec4 SCROLLBAR_BG;
	ImVec4 SCROLLBAR_GRAB;
	ImVec4 SCROLLBAR_GRAB_HOVERED;
	ImVec4 SCROLLBAR_GRAB_ACTIVE;

	ImVec4 CHECKMARK;

	ImVec4 SLIDER_GRAB;
	ImVec4 SLIDER_GRAB_ACTIVE;

	ImVec4 BUTTON;
	ImVec4 BUTTON_HOVERED;
	ImVec4 BUTTON_ACTIVE;

	ImVec4 HEADER;
	ImVec4 HEADER_HOVERED;
	ImVec4 HEADER_ACTIVE;

	ImVec4 SEPARATOR;
	ImVec4 SEPARATOR_HOVERED;
	ImVec4 SEPARATOR_ACTIVE;

	ImVec4 RESIZE_GRIP;
	ImVec4 RESIZE_GRIP_HOVERED;
	ImVec4 RESIZE_GRIP_ACTIVE;

	ImVec4 TAB;
	ImVec4 TAB_HOVERED;
	ImVec4 TAB_ACTIVE;
	ImVec4 TAB_UNFOCUSED;
	ImVec4 TAB_UNFOCUSED_ACTIVE;

	ImVec4 PLOT_LINES;
	ImVec4 PLOT_LINES_HOVERED;
	ImVec4 PLOT_HISTOGRAM;
	ImVec4 PLOT_HISTOGRAM_HOVERED;

	ImVec4 TABLE_HEADER_BG;
	ImVec4 TABLE_BORDER_STRONG;
	ImVec4 TABLE_BORDER_LIGHT;
	ImVec4 TABLE_ROW_BG;
	ImVec4 TABLE_ROW_BG_ALT;

	ImVec4 TEXT_SELECTED_BG;
	ImVec4 DRAG_DROP_TARGET;

	ImVec4 NAV_HIGHLIGHT;
	ImVec4 NAV_WINDOWING_HIGHLIGHT;
	ImVec4 NAV_WINDOWING_DIM_BG;
	ImVec4 MODAL_WINDOW_DIM_BG;
};

extern EditorTheme DarkTheme;

